name: Build

on:
  push:
    branches:
      - main

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
          - {os: macos-latest, arch: x86_64, build: "*"}
          - {os: macos-latest, arch: arm64, build: "*"}
          - {os: windows-latest, arch: AMD64, build: "*"}
          - {os: windows-latest, arch: x86, build: "*"}          
          - {os: ubuntu-latest, arch: x86_64, build: "*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[61]-manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[72]-manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[83]-manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[94]-manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[05]-manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[61]-musllinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[72]-musllinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[83]-musllinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[94]-musllinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*[05]-musllinux*"}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.21.1

            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse
              env:
                CIBW_BUILD_VERBOSITY: 1
                CIBW_ARCHS: ${{ matrix.arch }}
                CIBW_BUILD: ${{ matrix.build }}

            - name: Upload built wheels as artifacts
              uses: actions/upload-artifact@v3
              with:
                name: wheels
                path: wheelhouse/*

    upload_wheels:
        name: Upload wheels
        runs-on: ubuntu-latest  # Use any available OS; it can be a dedicated upload job
        needs: build_wheels     # Ensure this runs after the wheels are built
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              submodules: recursive

          - name: Download built wheels
            uses: actions/download-artifact@v3
            with:
              name: wheels
              path: wheelhouse

          - name: Install Twine
            run: python -m pip install twine

          - name: Upload to PyPI
            run: |
              twine upload wheelhouse/*
            env:
              TWINE_USERNAME: __token__
              TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}